; Auto-generated. Do not edit!


(cl:in-package lane_det-msg)


;//! \htmlinclude lane_detection.msg.html

(cl:defclass <lane_detection> (roslisp-msg-protocol:ros-message)
  ((left_1
    :reader left_1
    :initarg :left_1
    :type (cl:vector geometry_msgs-msg:Point)
   :initform (cl:make-array 0 :element-type 'geometry_msgs-msg:Point :initial-element (cl:make-instance 'geometry_msgs-msg:Point)))
   (left_0
    :reader left_0
    :initarg :left_0
    :type (cl:vector geometry_msgs-msg:Point)
   :initform (cl:make-array 0 :element-type 'geometry_msgs-msg:Point :initial-element (cl:make-instance 'geometry_msgs-msg:Point)))
   (right_0
    :reader right_0
    :initarg :right_0
    :type (cl:vector geometry_msgs-msg:Point)
   :initform (cl:make-array 0 :element-type 'geometry_msgs-msg:Point :initial-element (cl:make-instance 'geometry_msgs-msg:Point)))
   (right_1
    :reader right_1
    :initarg :right_1
    :type (cl:vector geometry_msgs-msg:Point)
   :initform (cl:make-array 0 :element-type 'geometry_msgs-msg:Point :initial-element (cl:make-instance 'geometry_msgs-msg:Point)))
   (coeff_left_1
    :reader coeff_left_1
    :initarg :coeff_left_1
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (coeff_left_0
    :reader coeff_left_0
    :initarg :coeff_left_0
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (coeff_right_0
    :reader coeff_right_0
    :initarg :coeff_right_0
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (coeff_right_1
    :reader coeff_right_1
    :initarg :coeff_right_1
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass lane_detection (<lane_detection>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <lane_detection>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'lane_detection)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name lane_det-msg:<lane_detection> is deprecated: use lane_det-msg:lane_detection instead.")))

(cl:ensure-generic-function 'left_1-val :lambda-list '(m))
(cl:defmethod left_1-val ((m <lane_detection>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lane_det-msg:left_1-val is deprecated.  Use lane_det-msg:left_1 instead.")
  (left_1 m))

(cl:ensure-generic-function 'left_0-val :lambda-list '(m))
(cl:defmethod left_0-val ((m <lane_detection>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lane_det-msg:left_0-val is deprecated.  Use lane_det-msg:left_0 instead.")
  (left_0 m))

(cl:ensure-generic-function 'right_0-val :lambda-list '(m))
(cl:defmethod right_0-val ((m <lane_detection>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lane_det-msg:right_0-val is deprecated.  Use lane_det-msg:right_0 instead.")
  (right_0 m))

(cl:ensure-generic-function 'right_1-val :lambda-list '(m))
(cl:defmethod right_1-val ((m <lane_detection>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lane_det-msg:right_1-val is deprecated.  Use lane_det-msg:right_1 instead.")
  (right_1 m))

(cl:ensure-generic-function 'coeff_left_1-val :lambda-list '(m))
(cl:defmethod coeff_left_1-val ((m <lane_detection>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lane_det-msg:coeff_left_1-val is deprecated.  Use lane_det-msg:coeff_left_1 instead.")
  (coeff_left_1 m))

(cl:ensure-generic-function 'coeff_left_0-val :lambda-list '(m))
(cl:defmethod coeff_left_0-val ((m <lane_detection>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lane_det-msg:coeff_left_0-val is deprecated.  Use lane_det-msg:coeff_left_0 instead.")
  (coeff_left_0 m))

(cl:ensure-generic-function 'coeff_right_0-val :lambda-list '(m))
(cl:defmethod coeff_right_0-val ((m <lane_detection>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lane_det-msg:coeff_right_0-val is deprecated.  Use lane_det-msg:coeff_right_0 instead.")
  (coeff_right_0 m))

(cl:ensure-generic-function 'coeff_right_1-val :lambda-list '(m))
(cl:defmethod coeff_right_1-val ((m <lane_detection>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lane_det-msg:coeff_right_1-val is deprecated.  Use lane_det-msg:coeff_right_1 instead.")
  (coeff_right_1 m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <lane_detection>) ostream)
  "Serializes a message object of type '<lane_detection>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'left_1))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'left_1))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'left_0))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'left_0))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'right_0))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'right_0))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'right_1))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'right_1))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'coeff_left_1))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'coeff_left_1))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'coeff_left_0))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'coeff_left_0))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'coeff_right_0))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'coeff_right_0))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'coeff_right_1))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'coeff_right_1))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <lane_detection>) istream)
  "Deserializes a message object of type '<lane_detection>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'left_1) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'left_1)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'geometry_msgs-msg:Point))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'left_0) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'left_0)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'geometry_msgs-msg:Point))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'right_0) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'right_0)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'geometry_msgs-msg:Point))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'right_1) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'right_1)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'geometry_msgs-msg:Point))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'coeff_left_1) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'coeff_left_1)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'coeff_left_0) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'coeff_left_0)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'coeff_right_0) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'coeff_right_0)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'coeff_right_1) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'coeff_right_1)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<lane_detection>)))
  "Returns string type for a message object of type '<lane_detection>"
  "lane_det/lane_detection")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'lane_detection)))
  "Returns string type for a message object of type 'lane_detection"
  "lane_det/lane_detection")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<lane_detection>)))
  "Returns md5sum for a message object of type '<lane_detection>"
  "6a8ccbd1be031a9ebcd2bcf06c6e28fd")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'lane_detection)))
  "Returns md5sum for a message object of type 'lane_detection"
  "6a8ccbd1be031a9ebcd2bcf06c6e28fd")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<lane_detection>)))
  "Returns full string definition for message of type '<lane_detection>"
  (cl:format cl:nil "geometry_msgs/Point[] left_1~%geometry_msgs/Point[] left_0~%geometry_msgs/Point[] right_0~%geometry_msgs/Point[] right_1~%float32[] coeff_left_1~%float32[] coeff_left_0~%float32[] coeff_right_0~%float32[] coeff_right_1~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'lane_detection)))
  "Returns full string definition for message of type 'lane_detection"
  (cl:format cl:nil "geometry_msgs/Point[] left_1~%geometry_msgs/Point[] left_0~%geometry_msgs/Point[] right_0~%geometry_msgs/Point[] right_1~%float32[] coeff_left_1~%float32[] coeff_left_0~%float32[] coeff_right_0~%float32[] coeff_right_1~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <lane_detection>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'left_1) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'left_0) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'right_0) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'right_1) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'coeff_left_1) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'coeff_left_0) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'coeff_right_0) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'coeff_right_1) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <lane_detection>))
  "Converts a ROS message object to a list"
  (cl:list 'lane_detection
    (cl:cons ':left_1 (left_1 msg))
    (cl:cons ':left_0 (left_0 msg))
    (cl:cons ':right_0 (right_0 msg))
    (cl:cons ':right_1 (right_1 msg))
    (cl:cons ':coeff_left_1 (coeff_left_1 msg))
    (cl:cons ':coeff_left_0 (coeff_left_0 msg))
    (cl:cons ':coeff_right_0 (coeff_right_0 msg))
    (cl:cons ':coeff_right_1 (coeff_right_1 msg))
))
